
services:
  web:
    image: johannafld/flask_app_johanna:${APP_VERSION} 
    build: .
    environment:
      - DB_HOST=db  
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASS=mypassword
    ports:
      - "5000:5000"
    volumes:
     - ./main.py:/app/main.py
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:latest
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser"]
      interval: 10s
      retries: 5    
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - $HOME/postgresql_data:/var/lib/postgresql/data
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge