
services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - $HOME/postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  web:
    image: johannafld/flask_app_johanna:${APP_VERSION} 
    build: .
    environment:
      - DB_HOST=db
    ports:
      - "5000:5000"
    volumes:
      - ./main.py:/app/main.py
    depends_on:
      - db
  
 
