name: CI/CD Pipeline

# Déclenche le workflow sur un push ou pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Set up Python and install dependencies
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 3. Run tests
    - name: Run unit tests
      run: |
        pytest
